server {
  listen 80;
  server_name _;

  location /api {
    default_type application/json;
    alias /usr/share/nginx/html/api.json;
  }

  location /version {
    default_type application/json;
    alias /usr/share/nginx/html/version.json;
  }

  location / {
    default_type application/json;
    return 200 '{"kind":"APIServerMock","anonymousAccess":true,"trainingOnly":true}';
  }
}
