events {}
http {
    include /etc/nginx/mime.types;
    server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            
            # [함정 1] 원래는 index.html을 찾아야 하지만, 이름을 일부러 틀리게 적습니다.
            index landing.html; 
            
            # [함정 2] 인덱스 파일을 못 찾으면 폴더 목록을 보여주도록 설정 (취약점)
            autoindex on;
            autoindex_exact_size off;
            autoindex_localtime on;
        }
    }
}