server:
  port: 8080

spring:
  application:
    name: holo-comm-server

management:
  endpoints:
    web:
      exposure:
        include: health,info

holo:
  public-base-url: http://localhost:9066
