server:
  port: 9094

spring:
  application:
    name: SPACE-MINING
  datasource:
    url: jdbc:h2:mem:spacemining;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 6
      minimum-idle: 2
      connection-timeout: 1200
      leak-detection-threshold: 2000
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  file:
    name: logs/space-mining-operations.log
  level:
    com.spacemining: INFO
