package com.demo.dbfaultservice.service;

import jakarta.annotation.PostConstruct;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ThreadLocalRandom;
import java.util.concurrent.atomic.AtomicInteger;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

@Service
public class FaultSimulationService {

  private static final DateTimeFormatter TIME_FORMATTER = DateTimeFormatter.ofPattern("HH:mm:ss");
  private final JdbcTemplate jdbcTemplate;
  private final LinkedList<String> sqlLog = new LinkedList<>();
  private final AtomicInteger deadlockRound = new AtomicInteger(0);
  private volatile long deadlockUntilMillis = 0L;

  public FaultSimulationService(JdbcTemplate jdbcTemplate) {
    this.jdbcTemplate = jdbcTemplate;
  }

  @PostConstruct
  void init() {
    jdbcTemplate.execute("""
        CREATE TABLE IF NOT EXISTS accounts (
          id BIGINT PRIMARY KEY,
          owner VARCHAR(80) NOT NULL,
          balance DECIMAL(19,2) NOT NULL,
          password VARCHAR(64) NOT NULL,
          account_number VARCHAR(40) NOT NULL,
          last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """);
    jdbcTemplate.execute("""
        CREATE TABLE IF NOT EXISTS transfer_log (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          from_id BIGINT,
          to_id BIGINT,
          amount DECIMAL(19,2),
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """);

    Integer count = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM accounts", Integer.class);
    if (count != null && count == 0) {
      jdbcTemplate.update("INSERT INTO accounts(id, owner, balance, password, account_number) VALUES(1,'Alpha Growth Fund',1250000.00,'trader!2026','110-889-4321')");
      jdbcTemplate.update("INSERT INTO accounts(id, owner, balance, password, account_number) VALUES(2,'Prime Treasury Pool',980000.00,'vault#7712','220-101-9191')");
      jdbcTemplate.update("INSERT INTO accounts(id, owner, balance, password, account_number) VALUES(3,'Client Escrow Desk',730000.00,'escrow_pw','330-551-8204')");
      jdbcTemplate.update("INSERT INTO accounts(id, owner, balance, password, account_number) VALUES(4,'Structured Product Desk',1800000.00,'sp_admin_pass','440-884-1090')");
      jdbcTemplate.update("INSERT INTO accounts(id, owner, balance, password, account_number) VALUES(5,'Derivatives Clearing',620000.00,'deriv-ops','550-120-4482')");
      jdbcTemplate.update("INSERT INTO accounts(id, owner, balance, password, account_number) VALUES(6,'FX Liquidity Hub',860000.00,'fx-core','660-271-0045')");
    }
    logSql("SELECT id, owner, balance, password, account_number FROM accounts WHERE account_number='110-889-4321' AND password='trader!2026';");
  }

  @Scheduled(fixedRate = 18000)
  void triggerDeadlockWindow() {
    deadlockUntilMillis = System.currentTimeMillis() + 7000;
    int round = deadlockRound.incrementAndGet();
    logSql("/* Deadlock Detected */ UPDATE accounts SET balance=balance WHERE id IN (1,2); -- round " + round);
  }

  public Map<String, Object> getDeadlockStatus() {
    boolean active = isDeadlockActive();
    Map<String, Object> response = new HashMap<>();
    response.put("index", 55);
    response.put("active", active);
    response.put("message", active ? "Deadlock Detected: lock wait timeout on accounts table" : "No active deadlock");
    response.put("freezeDataUpdates", active);
    response.put("round", deadlockRound.get());
    return response;
  }

  public Map<String, Object> simulateDirtyReadTransfer(long fromId, long toId, double amount) {
    String qFrom = "SELECT balance FROM accounts WHERE id = " + fromId;
    String qTo = "SELECT balance FROM accounts WHERE id = " + toId;
    logSql(qFrom + ";");
    logSql(qTo + ";");

    Double fromBalance = jdbcTemplate.queryForObject("SELECT balance FROM accounts WHERE id = ?", Double.class, fromId);
    Double toBalance = jdbcTemplate.queryForObject("SELECT balance FROM accounts WHERE id = ?", Double.class, toId);
    if (fromBalance == null || toBalance == null) {
      throw new IllegalArgumentException("Invalid account id");
    }
    if (amount <= 0 || fromBalance < amount) {
      throw new IllegalArgumentException("Transfer amount is invalid");
    }

    double uncommittedSourceBalance = fromBalance - amount;
    double dirtyReadBalanceSeenByOtherSession = uncommittedSourceBalance; // index 52 fault simulation
    logSql("/* Session-B Dirty Read */ SELECT balance FROM accounts WHERE id = " + fromId + " -- saw " + dirtyReadBalanceSeenByOtherSession + " before COMMIT;");

    sleepSilently(900);

    jdbcTemplate.update("UPDATE accounts SET balance = ?, last_updated = CURRENT_TIMESTAMP WHERE id = ?", uncommittedSourceBalance, fromId);
    jdbcTemplate.update("UPDATE accounts SET balance = ?, last_updated = CURRENT_TIMESTAMP WHERE id = ?", toBalance + amount, toId);
    jdbcTemplate.update("INSERT INTO transfer_log(from_id, to_id, amount) VALUES(?,?,?)", fromId, toId, amount);
    logSql("UPDATE accounts SET balance=" + uncommittedSourceBalance + " WHERE id=" + fromId + ";");
    logSql("UPDATE accounts SET balance=" + (toBalance + amount) + " WHERE id=" + toId + ";");
    logSql("INSERT INTO transfer_log(from_id, to_id, amount) VALUES(" + fromId + "," + toId + "," + amount + ");");

    Map<String, Object> response = new HashMap<>();
    response.put("index", 52);
    response.put("status", "committed");
    response.put("fromId", fromId);
    response.put("toId", toId);
    response.put("amount", amount);
    response.put("dirtyReadObserved", true);
    response.put("dirtyReadSessionBalance", round2(dirtyReadBalanceSeenByOtherSession));
    response.put("committedFromBalance", round2(uncommittedSourceBalance));
    response.put("committedToBalance", round2(toBalance + amount));
    response.put("message", "Dirty Read / Isolation Leak simulated before transfer commit");
    return response;
  }

  public Map<String, Object> getAccountsWithNPlusOne(int requestedSize) {
    int size = Math.max(2, Math.min(requestedSize, 10));
    logSql("SELECT id FROM accounts ORDER BY id LIMIT " + size + ";");
    List<Long> ids = jdbcTemplate.query("SELECT id FROM accounts ORDER BY id LIMIT ?", (rs, rowNum) -> rs.getLong("id"), size);

    List<Map<String, Object>> rows = new ArrayList<>();
    long totalDelay = 0L;
    int queryCount = 1;
    boolean freezeUpdates = isDeadlockActive();

    for (int i = 0; i < ids.size(); i++) {
      long id = ids.get(i);
      queryCount++;
      logSql("SELECT id, owner, balance, password, account_number FROM accounts WHERE id = " + id + ";");
      Map<String, Object> account = jdbcTemplate.queryForMap("SELECT id, owner, balance, password, account_number, last_updated FROM accounts WHERE id = ?", id);
      rows.add(account);

      long exponentialDelay = Math.min(1200, (long) (Math.pow(2, i) * 35));
      totalDelay += exponentialDelay;
      sleepSilently(exponentialDelay);

      if (!freezeUpdates) {
        jdbcTemplate.update("UPDATE accounts SET last_updated = CURRENT_TIMESTAMP WHERE id = ?", id);
        queryCount++;
        logSql("UPDATE accounts SET last_updated=CURRENT_TIMESTAMP WHERE id = " + id + ";");
      }
    }

    Map<String, Object> payload = new HashMap<>();
    payload.put("index", 50);
    payload.put("size", size);
    payload.put("queryCount", queryCount);
    payload.put("delayMs", totalDelay);
    payload.put("accounts", rows);
    payload.put("message", "N+1 query pattern causes exponentially increasing latency");
    payload.put("updatesFrozenByDeadlock", freezeUpdates);
    return payload;
  }

  public List<Map<String, Object>> getLatencySeries() {
    List<Map<String, Object>> points = new ArrayList<>();
    boolean deadlock = isDeadlockActive();
    int nPlusOnePenalty = ThreadLocalRandom.current().nextInt(30, 200);

    for (int i = 0; i < 20; i++) {
      int base = 150 + ThreadLocalRandom.current().nextInt(30, 130);
      int latency = base + (i > 12 ? nPlusOnePenalty : nPlusOnePenalty / 3);
      if (deadlock && i % 3 == 0) {
        latency += 250;
      }
      Map<String, Object> p = new HashMap<>();
      p.put("time", LocalTime.now().minusMinutes(19 - i).format(TIME_FORMATTER));
      p.put("latency", latency);
      points.add(p);
    }
    return points;
  }

  public List<String> getSqlLog() {
    return List.copyOf(sqlLog);
  }

  private void logSql(String sql) {
    String entry = "[" + LocalTime.now().format(TIME_FORMATTER) + "] " + sql;
    synchronized (sqlLog) {
      sqlLog.addFirst(entry);
      while (sqlLog.size() > 40) {
        sqlLog.removeLast();
      }
    }
  }

  private boolean isDeadlockActive() {
    return System.currentTimeMillis() < deadlockUntilMillis;
  }

  private void sleepSilently(long millis) {
    try {
      Thread.sleep(millis);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }
  }

  private double round2(double value) {
    return Math.round(value * 100.0) / 100.0;
  }
}
