events { worker_connections 1024; }
http {
    include /etc/nginx/mime.types;
    server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }
        location /api/ {
            proxy_pass http://backend-9032:8080;
            # 인프라 결함 유도: 타임아웃을 1초로 짧게 잡아 백엔드 5초 지연 시 504 에러 발생
            proxy_read_timeout 1s;
            proxy_connect_timeout 1s;
        }
    }
}