server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: smart-escrow-backend-9089

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
