server {
  listen 9068;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  add_header Cross-Origin-Opener-Policy same-origin always;
  add_header Cross-Origin-Embedder-Policy require-corp always;

  location /api/ {
    proxy_pass http://backend:8080/api/;
    proxy_http_version 1.1;
    proxy_set_header Host localhost:9068;
    proxy_set_header X-Forwarded-Host localhost:9068;
    proxy_set_header X-Forwarded-Port 9068;
    proxy_set_header X-Forwarded-Proto http;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
