server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # [오류 1] 디렉토리 리스팅 방치
    # 관리자가 내부 공유용 폴더 설정을 실수하여 파일 목록이 노출됨
    location /internal/ {
        alias /etc/nginx/; # Nginx 설정 파일들이 있는 곳을 연결
        autoindex on;      # 파일 목록 보기 활성화
    }

    location /api/ {
        proxy_pass http://backend:8080;
    }
}