events {}
http {
    include /etc/nginx/mime.types;
    server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            # 다시 index.html을 찾도록 정상화합니다.
            index index.html; 
            try_files $uri $uri/ /index.html;
        }
        location /api/ {
            proxy_pass http://backend:5001;
        }
    }
}