server:
  port: 8080

spring:
  application:
    name: health-pill-backend

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

health-pill:
  public-origin: http://localhost:9085
