events {}
http {
    include /etc/nginx/mime.types;
    
    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # 함정: 실제 백엔드(5001)가 아닌 5000번 포트로 연결해 502 에러 유발
        location /api/ {
            proxy_pass http://backend:5000; 
        }
    }
}